name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infrastructure
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HG: ${{ secrets.HG}}
        run: |
          git remote add space https://Iulia-leeloo:$HG@huggingface.co/spaces/Iulia-leeloo/hugging-face-demo
          git push --force space main

 
          # Force push to the Space's main branch
         
